# Generated by Django 5.0.3 on 2024-07-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
